# Site Settings
title: Deadbolt Password Generator          # Your website's title
description: A sample Jekyll site # A short description

# Build Settings
sass:
  sass_dir: assets/_sass
  style: compressed